language: go
go:
  1.11

jobs:
  include:
    - stage: test
      script: make deps test
    - stage: docker build
      script: make docker build

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    script:
        - make docker-deploy
    skip_cleanup: true
    on:
      branch: dev

  - provider: script
    script:
        - make docker-deploy
    skip_cleanup: true
    on:
      tags: true
