// Code generated by protoc-gen-go. DO NOT EDIT.
// source: birthday.proto

package birthdaypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetBirthdayRequest struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Month                int32    `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBirthdayRequest) Reset()         { *m = SetBirthdayRequest{} }
func (m *SetBirthdayRequest) String() string { return proto.CompactTextString(m) }
func (*SetBirthdayRequest) ProtoMessage()    {}
func (*SetBirthdayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_birthday_5a01add40f2387f4, []int{0}
}
func (m *SetBirthdayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBirthdayRequest.Unmarshal(m, b)
}
func (m *SetBirthdayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBirthdayRequest.Marshal(b, m, deterministic)
}
func (dst *SetBirthdayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBirthdayRequest.Merge(dst, src)
}
func (m *SetBirthdayRequest) XXX_Size() int {
	return xxx_messageInfo_SetBirthdayRequest.Size(m)
}
func (m *SetBirthdayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBirthdayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBirthdayRequest proto.InternalMessageInfo

func (m *SetBirthdayRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *SetBirthdayRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetBirthdayRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *SetBirthdayRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type UserBirthday struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId             string   `protobuf:"bytes,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Month                int32    `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBirthday) Reset()         { *m = UserBirthday{} }
func (m *UserBirthday) String() string { return proto.CompactTextString(m) }
func (*UserBirthday) ProtoMessage()    {}
func (*UserBirthday) Descriptor() ([]byte, []int) {
	return fileDescriptor_birthday_5a01add40f2387f4, []int{1}
}
func (m *UserBirthday) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBirthday.Unmarshal(m, b)
}
func (m *UserBirthday) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBirthday.Marshal(b, m, deterministic)
}
func (dst *UserBirthday) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBirthday.Merge(dst, src)
}
func (m *UserBirthday) XXX_Size() int {
	return xxx_messageInfo_UserBirthday.Size(m)
}
func (m *UserBirthday) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBirthday.DiscardUnknown(m)
}

var xxx_messageInfo_UserBirthday proto.InternalMessageInfo

func (m *UserBirthday) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserBirthday) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *UserBirthday) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserBirthday) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *UserBirthday) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type SetBirthdayReply struct {
	Birthday             *UserBirthday `protobuf:"bytes,1,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetBirthdayReply) Reset()         { *m = SetBirthdayReply{} }
func (m *SetBirthdayReply) String() string { return proto.CompactTextString(m) }
func (*SetBirthdayReply) ProtoMessage()    {}
func (*SetBirthdayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_birthday_5a01add40f2387f4, []int{2}
}
func (m *SetBirthdayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBirthdayReply.Unmarshal(m, b)
}
func (m *SetBirthdayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBirthdayReply.Marshal(b, m, deterministic)
}
func (dst *SetBirthdayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBirthdayReply.Merge(dst, src)
}
func (m *SetBirthdayReply) XXX_Size() int {
	return xxx_messageInfo_SetBirthdayReply.Size(m)
}
func (m *SetBirthdayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBirthdayReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetBirthdayReply proto.InternalMessageInfo

func (m *SetBirthdayReply) GetBirthday() *UserBirthday {
	if m != nil {
		return m.Birthday
	}
	return nil
}

type QueryBirthdaysRequest struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBirthdaysRequest) Reset()         { *m = QueryBirthdaysRequest{} }
func (m *QueryBirthdaysRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBirthdaysRequest) ProtoMessage()    {}
func (*QueryBirthdaysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_birthday_5a01add40f2387f4, []int{3}
}
func (m *QueryBirthdaysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBirthdaysRequest.Unmarshal(m, b)
}
func (m *QueryBirthdaysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBirthdaysRequest.Marshal(b, m, deterministic)
}
func (dst *QueryBirthdaysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBirthdaysRequest.Merge(dst, src)
}
func (m *QueryBirthdaysRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBirthdaysRequest.Size(m)
}
func (m *QueryBirthdaysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBirthdaysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBirthdaysRequest proto.InternalMessageInfo

func (m *QueryBirthdaysRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *QueryBirthdaysRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *QueryBirthdaysRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type QueryBirthdaysReply struct {
	Birthdays            []*UserBirthday `protobuf:"bytes,1,rep,name=birthdays,proto3" json:"birthdays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryBirthdaysReply) Reset()         { *m = QueryBirthdaysReply{} }
func (m *QueryBirthdaysReply) String() string { return proto.CompactTextString(m) }
func (*QueryBirthdaysReply) ProtoMessage()    {}
func (*QueryBirthdaysReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_birthday_5a01add40f2387f4, []int{4}
}
func (m *QueryBirthdaysReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBirthdaysReply.Unmarshal(m, b)
}
func (m *QueryBirthdaysReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBirthdaysReply.Marshal(b, m, deterministic)
}
func (dst *QueryBirthdaysReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBirthdaysReply.Merge(dst, src)
}
func (m *QueryBirthdaysReply) XXX_Size() int {
	return xxx_messageInfo_QueryBirthdaysReply.Size(m)
}
func (m *QueryBirthdaysReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBirthdaysReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBirthdaysReply proto.InternalMessageInfo

func (m *QueryBirthdaysReply) GetBirthdays() []*UserBirthday {
	if m != nil {
		return m.Birthdays
	}
	return nil
}

func init() {
	proto.RegisterType((*SetBirthdayRequest)(nil), "birthdaypb.SetBirthdayRequest")
	proto.RegisterType((*UserBirthday)(nil), "birthdaypb.UserBirthday")
	proto.RegisterType((*SetBirthdayReply)(nil), "birthdaypb.SetBirthdayReply")
	proto.RegisterType((*QueryBirthdaysRequest)(nil), "birthdaypb.QueryBirthdaysRequest")
	proto.RegisterType((*QueryBirthdaysReply)(nil), "birthdaypb.QueryBirthdaysReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BirthdayClient is the client API for Birthday service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BirthdayClient interface {
	SetBirthday(ctx context.Context, in *SetBirthdayRequest, opts ...grpc.CallOption) (*SetBirthdayReply, error)
	Query(ctx context.Context, in *QueryBirthdaysRequest, opts ...grpc.CallOption) (*QueryBirthdaysReply, error)
}

type birthdayClient struct {
	cc *grpc.ClientConn
}

func NewBirthdayClient(cc *grpc.ClientConn) BirthdayClient {
	return &birthdayClient{cc}
}

func (c *birthdayClient) SetBirthday(ctx context.Context, in *SetBirthdayRequest, opts ...grpc.CallOption) (*SetBirthdayReply, error) {
	out := new(SetBirthdayReply)
	err := c.cc.Invoke(ctx, "/birthdaypb.Birthday/SetBirthday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *birthdayClient) Query(ctx context.Context, in *QueryBirthdaysRequest, opts ...grpc.CallOption) (*QueryBirthdaysReply, error) {
	out := new(QueryBirthdaysReply)
	err := c.cc.Invoke(ctx, "/birthdaypb.Birthday/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BirthdayServer is the server API for Birthday service.
type BirthdayServer interface {
	SetBirthday(context.Context, *SetBirthdayRequest) (*SetBirthdayReply, error)
	Query(context.Context, *QueryBirthdaysRequest) (*QueryBirthdaysReply, error)
}

func RegisterBirthdayServer(s *grpc.Server, srv BirthdayServer) {
	s.RegisterService(&_Birthday_serviceDesc, srv)
}

func _Birthday_SetBirthday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBirthdayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirthdayServer).SetBirthday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birthdaypb.Birthday/SetBirthday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirthdayServer).SetBirthday(ctx, req.(*SetBirthdayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Birthday_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBirthdaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BirthdayServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/birthdaypb.Birthday/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BirthdayServer).Query(ctx, req.(*QueryBirthdaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Birthday_serviceDesc = grpc.ServiceDesc{
	ServiceName: "birthdaypb.Birthday",
	HandlerType: (*BirthdayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBirthday",
			Handler:    _Birthday_SetBirthday_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Birthday_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "birthday.proto",
}

func init() { proto.RegisterFile("birthday.proto", fileDescriptor_birthday_5a01add40f2387f4) }

var fileDescriptor_birthday_5a01add40f2387f4 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xcd, 0x6e, 0x53, 0xd2, 0xa9, 0x94, 0x32, 0xfe, 0x61, 0x09, 0xa2, 0x31, 0xa7, 0x9e,
	0x72, 0xa8, 0xe2, 0x03, 0x78, 0xd2, 0x43, 0x0e, 0x46, 0x3c, 0x79, 0x6a, 0xc8, 0x42, 0x03, 0xd5,
	0xac, 0xbb, 0x1b, 0x61, 0x7d, 0x22, 0x1f, 0x53, 0xba, 0x76, 0x93, 0x54, 0xd3, 0xd2, 0x5b, 0x66,
	0x67, 0x98, 0xef, 0xcb, 0x8f, 0x81, 0x49, 0x5e, 0x4a, 0xbd, 0x2c, 0x16, 0x26, 0x11, 0xb2, 0xd2,
	0x15, 0x82, 0xab, 0x45, 0x1e, 0x0b, 0xc0, 0x67, 0xae, 0xef, 0x37, 0x0f, 0x19, 0xff, 0xa8, 0xb9,
	0xd2, 0x18, 0x42, 0xa0, 0xb8, 0xfc, 0xe4, 0xf2, 0xb1, 0x60, 0x5e, 0xe4, 0xcd, 0x46, 0x59, 0x53,
	0xe3, 0x39, 0x0c, 0x6b, 0x65, 0x3b, 0xc4, 0x76, 0x36, 0x15, 0x9e, 0x82, 0xff, 0x56, 0xbd, 0xeb,
	0x25, 0xa3, 0x91, 0x37, 0xf3, 0xb3, 0xdf, 0x02, 0xa7, 0x40, 0x8b, 0x85, 0x61, 0x03, 0xfb, 0xb6,
	0xfe, 0x8c, 0xbf, 0xe0, 0xf8, 0x45, 0x71, 0xe9, 0x90, 0x38, 0x01, 0x52, 0x3a, 0x0a, 0x29, 0x8b,
	0x2d, 0x36, 0xd9, 0xc9, 0xa6, 0xfd, 0xec, 0x41, 0x0f, 0xdb, 0x6f, 0xd9, 0x0f, 0x30, 0xdd, 0xfa,
	0x5b, 0xb1, 0x32, 0x78, 0x0b, 0x81, 0xcb, 0xc3, 0x5a, 0x8c, 0xe7, 0x2c, 0x69, 0x03, 0x4a, 0xba,
	0xae, 0x59, 0x33, 0x19, 0xbf, 0xc2, 0xd9, 0x53, 0xcd, 0xa5, 0x71, 0x2d, 0x75, 0x48, 0x74, 0x8d,
	0x26, 0xe9, 0xd1, 0xa4, 0xad, 0x66, 0x0a, 0x27, 0x7f, 0x97, 0xaf, 0x4d, 0xef, 0x60, 0xe4, 0xf8,
	0x8a, 0x79, 0x11, 0xdd, 0xab, 0xda, 0x8e, 0xce, 0xbf, 0x3d, 0x08, 0x9a, 0xb8, 0x53, 0x18, 0x77,
	0x22, 0xc0, 0xcb, 0xee, 0x82, 0xff, 0x97, 0x10, 0x5e, 0xec, 0xec, 0x8b, 0x95, 0x89, 0x8f, 0x30,
	0x05, 0xdf, 0xaa, 0xe2, 0x75, 0x77, 0xb0, 0x37, 0x9a, 0xf0, 0x6a, 0xdf, 0x88, 0x5d, 0x97, 0x0f,
	0xed, 0x85, 0xde, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x87, 0x42, 0x32, 0xd4, 0xb3, 0x02, 0x00,
	0x00,
}
